### ISSUE TITLE
Inferred type names are not finding "Swift." (amongst other things).

### ISSUE THREAD

**Issue by lickel** [outfoxx/swiftpoet#81] opened 2023-05-08 22:52 UTC
Updating Square/Wire from v1.3.1 => v1.5, I saw a regression where declared type names are regularly being expressed with their fully qualified name.

We're semi-frequently doing something to the effect of `io.outfoxx.swiftpoet.STRING.makeOptional().makeNotOptional()`; however, we're also directly `DeclaredTypeName.typeName("Wire.ProtoWriter")` in an extension, which similarly loses the understanding of Wire being imported.

It looks like only types used within an `extension` have this limitation?

https://github.com/square/wire/pull/2454

**Comment by lickel** [comment] 2023-05-09 00:48
Possibly related: if I use a `DeclaredTypeName` _only_ in an extension, it doesn't implicitly import the module, which is kind of unexpected.

**Comment by lickel** [comment] 2023-05-11 22:42
Certainly not all inclusive, but you'll notice the type `public enum CodingKeys : Swift.String, Swift.CodingKey`

[SwiftPoet-Sample.zip](https://github.com/outfoxx/swiftpoet/files/11456767/SwiftPoet-Sample.zip)

**Comment by lickel** [comment] 2023-05-11 22:43
Sorry if that gradle config is not portable.

The output file is:
`SwiftPoet-Sample/app/SwiftPoet-Sample.swift`

**Comment by dnkoutso** [comment] 2023-12-14 13:44
I _think_ this is caused by this https://github.com/outfoxx/swiftpoet/pull/55 change.

**Comment by dnkoutso** [comment] 2023-12-15 08:13
I think this is actually resolved with https://github.com/outfoxx/swiftpoet/pull/90

**Comment by kdubb** [comment] 2023-12-16 11:40
@dnkoutso Can you confirm this is fixed?

**Comment by dnkoutso** [comment] 2023-12-16 12:07
I believe it is. Will close for now.

**Closed by dnkoutso** 2023-12-16 12:07 UTC
